import type { FC, ReactNode } from "react";
import type { FigureProps } from "../../../types/topic";

const mono = { fill: "var(--ink)", fontFamily: "var(--font-mono, monospace)", fontSize: 11 };
const body = { fill: "var(--ink)", fontFamily: "var(--font-body, sans-serif)", fontSize: 12 };
const muted = { fill: "var(--muted)", fontFamily: "var(--font-body, sans-serif)", fontSize: 10 };

function Panel({ x, y, w, h, children, active = false }: { x: number; y: number; w: number; h: number; children: ReactNode; active?: boolean }) {
  return <g><rect x={x} y={y} width={w} height={h} rx="8" fill="var(--surface-2, var(--surface))" stroke={active ? "var(--teal)" : "var(--line)"} strokeWidth={active ? 3 : 1}/>{children}</g>;
}

const workflow = [["1","RADIOGRAFIA","matriz · margem · reação"],["2","RM LOCAL","compartimento · feixes"],["3","ESTADIAMENTO","tórax · doença sistêmica"],["4","PLANEJAMENTO","alvo + trajeto removível"],["5","BIÓPSIA","tecido representativo"],["6","CORRELAÇÃO","clínica + imagem + patologia"]] as const;
export const BiopsySequence: FC<FigureProps> = ({ className, title, activeStep }) => <svg viewBox="0 0 640 330" role="img" className={className}><title>{title ?? "Sequência diagnóstica antes da biópsia óssea"}</title><text x="320" y="24" textAnchor="middle" {...mono}>A BIÓPSIA É A ÚLTIMA ETAPA DO DIAGNÓSTICO</text>{workflow.map(([n,label,note],i)=>{const x=24+(i%3)*204;const y=50+Math.floor(i/3)*120;const on=!activeStep||activeStep===Number(n);return <g key={n} opacity={on?1:.32}><Panel x={x} y={y} w={184} h={94} active={activeStep===Number(n)}><circle cx={x+27} cy={y+29} r="15" fill="var(--surface)" stroke="var(--teal)" strokeWidth="2"/><text x={x+27} y={y+33} textAnchor="middle" {...mono}>{n}</text><text x={x+50} y={y+32} {...mono}>{label}</text><text x={x+14} y={y+66} {...muted}>{note}</text></Panel>{i<5&&i!==2&&<path d={`M${x+186} ${y+47} L${x+200} ${y+47}`} stroke="var(--teal)" strokeWidth="2"/>}</g>})}<text x="320" y="310" textAnchor="middle" {...body}>Discordância entre imagem e histologia exige revisão antes do tratamento.</text></svg>;

export const BiopsyTrack: FC<FigureProps> = ({ className, title }) => <svg viewBox="0 0 620 320" role="img" className={className}><title>{title ?? "Planejamento do trajeto da biópsia"}</title><text x="310" y="24" textAnchor="middle" {...mono}>TODO O TRAJETO DEVE SAIR COM A PEÇA</text><Panel x={24} y={48} w={270} h={224}><text x="159" y="76" textAnchor="middle" {...mono} fill="var(--teal)">TRAJETO ONCOLÓGICO</text><ellipse cx="164" cy="169" rx="62" ry="54" fill="var(--cortical)" opacity=".18" stroke="var(--cortical)" strokeWidth="3"/><path d="M46 168 L103 168" stroke="var(--teal)" strokeWidth="8"/><path d="M46 154 L46 182" stroke="var(--teal)" strokeWidth="3"/><rect x="74" y="98" width="164" height="142" rx="60" fill="none" stroke="var(--teal)" strokeWidth="2" strokeDasharray="7 5"/><text x="159" y="254" textAnchor="middle" {...muted}>curto · longitudinal · um compartimento</text></Panel><Panel x={326} y={48} w={270} h={224}><text x="461" y="76" textAnchor="middle" {...mono} fill="var(--cortical)">CONTAMINAÇÃO</text><ellipse cx="462" cy="169" rx="62" ry="54" fill="var(--cortical)" opacity=".18" stroke="var(--cortical)" strokeWidth="3"/><path d="M352 112 L420 150 M352 204 L422 183 M465 96 L465 116" stroke="var(--cortical)" strokeWidth="6"/><circle cx="526" cy="126" r="18" fill="none" stroke="var(--amber)" strokeWidth="5"/><path d="M493 170 Q535 195 565 222" fill="none" stroke="var(--cortical)" strokeWidth="8" opacity=".55"/><text x="461" y="254" textAnchor="middle" {...muted}>feixe · articulação · hematoma · dreno</text></Panel><text x="310" y="302" textAnchor="middle" {...body}>O menor caminho técnico pode ser o pior caminho oncológico.</text></svg>;

const methods = [["core","AGULHA GROSSA","primeira escolha","campo mínimo"],["incisional","INCISIONAL","se agulha falha","cicatriz + leito"],["excisional","EXCISIONAL","pequena e benigna","toda a lesão"]] as const;
export const BiopsyMethods: FC<FigureProps> = ({ className, title, variant }) => <svg viewBox="0 0 620 300" role="img" className={className}><title>{title ?? "Métodos de biópsia musculoesquelética"}</title><text x="310" y="24" textAnchor="middle" {...mono}>MÉTODO · VOLUME DE TECIDO · CAMPO CONTAMINADO</text>{methods.map(([key,label,note,field],i)=>{const x=20+i*202;const on=!variant||variant===key;return <g key={key} opacity={on?1:.3}><Panel x={x} y={50} w={184} h={202} active={variant===key}><text x={x+92} y="78" textAnchor="middle" {...mono}>{label}</text><ellipse cx={x+92} cy="145" rx="44" ry="36" fill="var(--cortical)" opacity=".2" stroke="var(--cortical)" strokeWidth="2"/>{i===0?<path d={`M${x+20} 145 L${x+55} 145`} stroke="var(--teal)" strokeWidth="5"/>:i===1?<path d={`M${x+40} 113 L${x+40} 177`} stroke="var(--teal)" strokeWidth="7"/>:<rect x={x+36} y="98" width="112" height="94" rx="40" fill="none" stroke="var(--teal)" strokeWidth="3" strokeDasharray="6 4"/>}<text x={x+92} y="214" textAnchor="middle" {...body}>{note}</text><text x={x+92} y="235" textAnchor="middle" {...muted}>{field}</text></Panel></g>})}<text x="310" y="282" textAnchor="middle" {...body}>Quanto maior o acesso, maior a área que deverá ser ressecada.</text></svg>;

export const BiopsySample: FC<FigureProps> = ({ className, title }) => <svg viewBox="0 0 600 300" role="img" className={className}><title>{title ?? "Distribuição da amostra de biópsia"}</title><text x="300" y="24" textAnchor="middle" {...mono}>PLANEJAR O DESTINO ANTES DE COLETAR</text><ellipse cx="300" cy="92" rx="58" ry="40" fill="var(--cortical)" opacity=".2" stroke="var(--cortical)" strokeWidth="3"/><text x="300" y="97" textAnchor="middle" {...body}>tecido viável</text>{[[36,"FORMALINA","histologia"],[180,"FRESCO","molecular"],[324,"ESTÉRIL","culturas"],[468,"LÂMINA","imprint / citologia"]].map(([x,label,note],i)=><g key={String(label)}><path d={`M300 132 Q${Number(x)+48} 154 ${Number(x)+48} 178`} fill="none" stroke={i===2?"var(--amber)":"var(--teal)"} strokeWidth="2"/><rect x={Number(x)} y="178" width="96" height="72" rx="8" fill="var(--surface-2, var(--surface))" stroke="var(--line)"/><text x={Number(x)+48} y="207" textAnchor="middle" {...mono}>{label}</text><text x={Number(x)+48} y="230" textAnchor="middle" {...muted}>{note}</text></g>)}<text x="300" y="282" textAnchor="middle" {...body}>Não colocar toda a amostra em formalina se infecção ou estudo molecular são possíveis.</text></svg>;

export const Compartment: FC<FigureProps> = ({ className, title }) => <svg viewBox="0 0 620 310" role="img" className={className}><title>{title ?? "Extensão intra e extracompartimental"}</title><text x="310" y="24" textAnchor="middle" {...mono}>T DESCREVE BARREIRA · NÃO TAMANHO</text>{[[24,"T1 · CONTIDO",false],[326,"T2 · EXTRACOMPARTIMENTAL",true]].map(([x,label,outside])=><Panel key={String(label)} x={Number(x)} y={48} w={270} h={220}><text x={Number(x)+135} y="76" textAnchor="middle" {...mono} fill={outside?"var(--cortical)":"var(--teal)"}>{label}</text><ellipse cx={Number(x)+135} cy="166" rx="83" ry="68" fill="var(--surface)" stroke="var(--ink-soft)" strokeWidth="12"/><ellipse cx={Number(x)+135} cy="166" rx={outside?74:42} ry={outside?58:34} fill="var(--cortical)" opacity=".24" stroke="var(--cortical)" strokeWidth="3"/>{outside&&<path d={`M${Number(x)+190} 121 Q${Number(x)+239} 112 ${Number(x)+240} 162 Q${Number(x)+220} 191 ${Number(x)+188} 190`} fill="var(--cortical)" opacity=".24" stroke="var(--cortical)" strokeWidth="3"/>}<text x={Number(x)+135} y="248" textAnchor="middle" {...muted}>{outside?"rompe córtex/fáscia e invade adjacente":"permanece dentro da barreira"}</text></Panel>)}<text x="310" y="294" textAnchor="middle" {...body}>Córtex, cartilagem e fáscia são barreiras anatômicas temporárias.</text></svg>;

const stages = [["IA","G1 T1"],["IB","G1 T2"],["IIA","G2 T1"],["IIB","G2 T2"],["III","M1"]] as const;
export const EnnekingStages: FC<FigureProps> = ({ className, title, variant }) => <svg viewBox="0 0 640 320" role="img" className={className}><title>{title ?? "Estágios de Enneking para sarcomas"}</title><text x="320" y="24" textAnchor="middle" {...mono}>GRAU + COMPARTIMENTO + METÁSTASE</text>{stages.map(([code,formula],i)=>{const x=24+i*122;const on=!variant||variant===code;return <g key={code} opacity={on?1:.28}><Panel x={x} y={52} w={108} h={180} active={variant===code}><circle cx={x+54} cy="91" r="25" fill="var(--surface)" stroke={code==="III"?"var(--cortical)":i<2?"var(--amber)":"var(--teal)"} strokeWidth="3"/><text x={x+54} y="96" textAnchor="middle" {...mono}>{code}</text><text x={x+54} y="140" textAnchor="middle" {...body}>{formula}</text><line x1={x+22} y1="158" x2={x+86} y2="158" stroke="var(--line)"/><text x={x+54} y="184" textAnchor="middle" {...muted}>{code==="III"?"qualquer G/T":i<2?"baixo grau":"alto grau"}</text><text x={x+54} y="206" textAnchor="middle" {...muted}>{code.endsWith("A")?"contido":code.endsWith("B")?"extracompart.":"metastático"}</text></Panel></g>})}<text x="320" y="265" textAnchor="middle" {...body}>A = intracompartimental · B = extracompartimental</text><text x="320" y="289" textAnchor="middle" {...muted}>Enneking orienta controle local; AJCC e protocolos do subtipo completam o estadiamento.</text></svg>;

export const BenignStages: FC<FigureProps> = ({ className, title, variant }) => <svg viewBox="0 0 600 300" role="img" className={className}><title>{title ?? "Estágios de Enneking para tumores benignos"}</title><text x="300" y="24" textAnchor="middle" {...mono}>BENIGNO NÃO SIGNIFICA BIOLOGICAMENTE IGUAL</text>{[[24,"1","LATENTE",34,"margem esclerótica"],[214,"2","ATIVO",50,"crescimento limitado"],[404,"3","AGRESSIVO",70,"córtex rompido"]].map(([x,code,label,r,note],i)=>{const on=!variant||variant===String(code);return <g key={String(code)} opacity={on?1:.28}><Panel x={Number(x)} y={52} w={172} h={196} active={variant===String(code)}><text x={Number(x)+86} y="80" textAnchor="middle" {...mono}>{code} · {label}</text><ellipse cx={Number(x)+86} cy="148" rx={Number(r)} ry={Number(r)*.68} fill="var(--teal)" opacity={.12+i*.06} stroke={i===2?"var(--cortical)":"var(--teal)"} strokeWidth="3" strokeDasharray={i===1?"6 4":undefined}/>{i===2&&<path d={`M${Number(x)+140} 132 L${Number(x)+162} 116`} stroke="var(--cortical)" strokeWidth="8"/>}<text x={Number(x)+86} y="218" textAnchor="middle" {...muted}>{note}</text></Panel></g>})}<text x="300" y="280" textAnchor="middle" {...body}>Observação · curetagem · controle local ampliado, conforme diagnóstico e local.</text></svg>;

export const Margins: FC<FigureProps> = ({ className, title }) => <svg viewBox="0 0 640 320" role="img" className={className}><title>{title ?? "Margens cirúrgicas de Enneking"}</title><text x="320" y="24" textAnchor="middle" {...mono}>PLANO DE DISSECÇÃO EM RELAÇÃO AO TUMOR E À ZONA REATIVA</text><g transform="translate(202 42)"><ellipse cx="118" cy="122" rx="68" ry="53" fill="var(--cortical)" opacity=".25" stroke="var(--cortical)" strokeWidth="3"/><ellipse cx="118" cy="122" rx="91" ry="72" fill="none" stroke="var(--amber)" strokeWidth="14" opacity=".25"/><ellipse cx="118" cy="122" rx="113" ry="92" fill="none" stroke="var(--teal)" strokeWidth="3"/><rect x="-18" y="3" width="272" height="238" rx="110" fill="none" stroke="var(--ink-soft)" strokeWidth="3" strokeDasharray="8 5"/></g>{[[24,78,"INTRALESIONAL","dentro do tumor","var(--cortical)"],[24,148,"MARGINAL","zona reativa","var(--amber)"],[468,78,"AMPLA","tecido normal","var(--teal)"],[468,148,"RADICAL","todo compartimento","var(--ink-soft)"]].map(([x,y,label,note,color])=><g key={String(label)}><line x1={Number(x)<300?Number(x)+130:Number(x)} y1={Number(y)} x2={Number(x)<300?215:424} y2={Number(y)} stroke={String(color)} strokeWidth="2"/><text x={Number(x)} y={Number(y)-6} {...mono} fill={String(color)}>{label}</text><text x={Number(x)} y={Number(y)+12} {...muted}>{note}</text></g>)}<text x="320" y="290" textAnchor="middle" {...body}>Margem planejada só se confirma após orientação e análise patológica da peça.</text></svg>;

export const figures: Record<string, FC<FigureProps>> = {
  "biopsia-lesao-ossea:sequencia": BiopsySequence,
  "biopsia-lesao-ossea:trajeto": BiopsyTrack,
  "biopsia-lesao-ossea:metodos": BiopsyMethods,
  "biopsia-lesao-ossea:amostra": BiopsySample,
  "estadiamento-enneking:compartimento": Compartment,
  "estadiamento-enneking:estagios": EnnekingStages,
  "estadiamento-enneking:benignos": BenignStages,
  "estadiamento-enneking:margens": Margins,
};
