import { defineTopic } from "../../types/topic";

export const topic = defineTopic({
  id: "esp-tornozelo-instabilidade-lateral",
  slug: "instabilidade-lateral-tornozelo",
  kind: "condicao",
  regionId: "esportiva-artroscopia",
  bone: "Tornozelo & pé",
  injury: "Instabilidade lateral crônica do tornozelo",
  title: "Instabilidade lateral do tornozelo",
  subtitle:
    "Diferenciar frouxidão mecânica de falha neuromuscular, tratar lesões associadas e reconstruir a anatomia somente após reabilitação adequada.",
  laterality: null,
  status: "complete",
  overview:
    "A instabilidade lateral crônica surge após entorses por inversão que deixam episódios de falseio, insegurança em terreno irregular e redução da função esportiva. Ela combina dois componentes em proporções variáveis: instabilidade mecânica, com frouxidão dos ligamentos laterais, e instabilidade funcional, com déficits de propriocepção, força, tempo de reação e controle proximal.\n\nO diagnóstico é clínico. A gaveta anterior pesquisa o ligamento talofibular anterior (LTFA); a inclinação talar em inversão avalia principalmente o ligamento calcaneofibular (LCF). É obrigatório examinar alinhamento em cavo-varo, sindesmose, tendões fibulares, articulação subtalar e lesão osteocondral do tálus. Radiografias com carga mostram alinhamento e artrose; estresse quantifica frouxidão em casos selecionados; RM mapeia lesões associadas, não substitui exame.\n\nA primeira linha é reabilitação estruturada por pelo menos três meses, com treino proprioceptivo, força dos fibulares, controle de salto/aterrissagem e suporte externo durante exposição de risco. Cirurgia é reservada ao falseio persistente com correlação mecânica e falha do tratamento. O reparo anatômico de Broström-Gould preserva movimento e é referência quando o tecido é adequado; reconstrução com enxerto é opção na revisão, frouxidão generalizada, grande deformidade ou tecido insuficiente.",
  keyFacts: [
    { label: "Ligamento inicial", value: "LTFA é o mais frequentemente lesionado" },
    { label: "Mecânica", value: "Gaveta anterior e inclinação talar" },
    { label: "Funcional", value: "Propriocepção, força e controle do movimento" },
    { label: "Primeira linha", value: "Reabilitação estruturada ≥ 3 meses" },
    { label: "Reparo padrão", value: "Broström-Gould anatômico" },
    { label: "Pesquisar", value: "Cavo-varo, osteocondral, fibulares e sindesmose" },
  ],
  anatomy: {
    text:
      "O complexo lateral possui LTFA, LCF e ligamento talofibular posterior. O LTFA vai da borda anterior da fíbula ao colo do tálus; fica mais vulnerável em flexão plantar e inversão e limita translação anterior e rotação interna do tálus. O LCF segue da ponta da fíbula ao calcâneo, cruza tornozelo e subtalar e fica tenso próximo da posição neutra/dorsiflexão. O talofibular posterior é robusto e costuma romper apenas em trauma grave.\n\nO retináculo inferior dos extensores recobre a cápsula anterolateral e é avançado no reforço de Gould. Os tendões fibulares passam posteriores à fíbula e atuam como estabilizadores dinâmicos; ruptura, subluxação ou lesão do retináculo superior pode simular ou acompanhar instabilidade. O nervo fibular superficial cruza o campo anterolateral e o nervo sural fica posterior.\n\nCavo-varo e primeiro raio em flexão plantar aumentam o momento de inversão. Instabilidade subtalar, lesão da sindesmose, impacto anterolateral e defeito osteocondral do tálus explicam dor ou falseio que não melhoram com reparo ligamentar isolado.",
    figureIds: ["instabilidade-lateral-tornozelo:anatomia", "instabilidade-lateral-tornozelo:cadeia-cinematica"],
  },
  classification: [
    {
      id: "componentes-instabilidade",
      name: "Componente predominante",
      basis: "Frouxidão ligamentar objetiva versus falha sensório-motora e episódios de falseio.",
      types: [
        { code: "Mecânica", label: "Frouxidão estrutural", description: "Gaveta/inclinação aumentadas, ligamentos alongados ou descontínuos e possível alteração em estresse.", figureId: "instabilidade-lateral-tornozelo:exame", figureVariant: "mecanica" },
        { code: "Funcional", label: "Controle neuromuscular deficiente", description: "Falseio com testes de frouxidão discretos, déficit de equilíbrio, reação fibular e confiança.", figureId: "instabilidade-lateral-tornozelo:cadeia-cinematica", figureVariant: "funcional" },
        { code: "Combinada", label: "Mecânica + funcional", description: "Apresentação mais comum na instabilidade crônica estabelecida; exige corrigir estrutura e função.", figureId: "instabilidade-lateral-tornozelo:cadeia-cinematica", figureVariant: "combinada" },
      ],
    },
  ],
  indications: {
    operative: [
      "Falseios recorrentes e limitação esportiva após pelo menos três meses de reabilitação estruturada.",
      "Frouxidão mecânica correlacionada aos sintomas e ao exame sob anestesia.",
      "Broström-Gould quando LTFA/LCF têm tecido reparável.",
      "Reconstrução anatômica com enxerto em revisão, tecido ruim, hiperlaxidão importante ou grande demanda.",
      "Tratamento concomitante de lesão osteocondral, fibulares, impacto ou deformidade relevante.",
    ],
    nonOperative: [
      "Primeiro episódio ou instabilidade crônica ainda sem programa adequado de reabilitação.",
      "Predomínio funcional sem frouxidão mecânica relevante.",
      "Paciente que recupera confiança e função com treino e suporte externo.",
      "Contraindicação cirúrgica ou baixa demanda com sintomas controláveis.",
    ],
    decisionNotes:
      "Operar apenas porque a RM descreve LTFA espessado ou irregular é erro. Confirmar falseio, demanda, gaveta/inclinação e falha de reabilitação que inclua progressão esportiva. Antes de reparar, identificar fatores de falha: frouxidão generalizada, cavo-varo, inclinação talar muito aumentada, sindesmose, lesão osteocondral e fibulares. O reforço com fita pode permitir progressão mais rápida em casos selecionados, mas não substitui tecido, alinhamento ou técnica e pode sobre-restringir a articulação.",
  },
  approaches: [
    {
      id: "lateral-brostrom",
      name: "Via lateral para Broström-Gould",
      indication: "Reparo anatômico aberto do LTFA e LCF com reforço retinacular.",
      interval: "Incisão curva anterior e distal à fíbula, proteção dos ramos do nervo fibular superficial, abertura capsular e identificação dos remanescentes ligamentares.",
      atRisk: ["Nervo fibular superficial", "Nervo sural posterior", "Tendões fibulares", "Cartilagem do tálus"],
      figureId: "instabilidade-lateral-tornozelo:brostrom",
    },
    {
      id: "artroscopia-tornozelo",
      name: "Portais artroscópicos anteriores",
      indication: "Inventário e tratamento de impacto, sinovite e lesão osteocondral associada.",
      interval: "Portal anteromedial junto ao tibial anterior e anterolateral sob transiluminação, lateral aos fibulares superficiais visíveis.",
      atRisk: ["Nervo fibular superficial", "Veia safena e nervo safeno medialmente", "Cartilagem tibiotalar"],
      figureId: "instabilidade-lateral-tornozelo:imagem",
    },
  ],
  technique: [
    { n: 1, title: "Confirmar instabilidade e fatores de falha", detail: "Examinar gaveta, inclinação, subtalar, sindesmose, fibulares e alinhamento. Sob anestesia, comparar com o lado oposto. Rever radiografias com carga, estresse quando útil e RM para lesões associadas.", figureId: "instabilidade-lateral-tornozelo:exame", tips: ["Documentar cavo-varo e frouxidão generalizada"], pitfalls: ["Tratar ligamento sem explicar dor associada"] },
    { n: 2, title: "Inventariar a articulação", detail: "Quando indicada, artroscopia identifica sinovite, impacto anterolateral, corpo livre e lesão osteocondral. Tratar a patologia relevante antes do reparo lateral, evitando desbridamento indiscriminado.", figureId: "instabilidade-lateral-tornozelo:imagem", tips: ["Correlacionar defeito osteocondral com sintomas"], pitfalls: ["Ignorar lesão intra-articular em tornozelo doloroso"] },
    { n: 3, title: "Expor e preparar os remanescentes", detail: "Proteger nervos cutâneos, abrir cápsula junto à fíbula e elevar LTFA/LCF com pequena manga periosteal. Preparar a borda fibular sem enfraquecer o maléolo.", figureId: "instabilidade-lateral-tornozelo:brostrom", tips: ["Manter tecido suficiente para imbricação"], pitfalls: ["Lesar nervo fibular superficial ou tendões fibulares"] },
    { n: 4, title: "Reparar LTFA e LCF anatomicamente", detail: "Reinserir remanescentes na fíbula com pontos transósseos ou âncoras. Tensionar LTFA em posição neutra e LCF com retropé corrigido, evitando excesso de inversão ou rotação.", figureId: "instabilidade-lateral-tornozelo:brostrom", tips: ["Manter tálus reduzido e retropé neutro ao tensionar"], pitfalls: ["Sobre-restrição ou reparo frouxo em flexão plantar"] },
    { n: 5, title: "Reforçar e corrigir fatores associados", detail: "Avançar retináculo inferior dos extensores sobre o reparo (Gould). Reconstruir com enxerto se tecido insuficiente e associar correção de cavo-varo ou tratamento dos fibulares quando necessário.", figureId: "instabilidade-lateral-tornozelo:brostrom", tips: ["O reforço retinacular protege sem substituir o reparo anatômico"], pitfalls: ["Ignorar deformidade que mantém momento de inversão"] },
    { n: 6, title: "Testar e vincular retorno a critérios", detail: "Repetir gaveta e inclinação, verificar amplitude e fechar sem tensão neural. A reabilitação progride de proteção para força, equilíbrio, salto e mudança de direção antes do retorno.", figureId: "instabilidade-lateral-tornozelo:retorno-esporte", tips: ["Comparar testes funcionais com o lado oposto"], pitfalls: ["Liberar esporte apenas por tempo"] },
  ],
  postop: {
    immobilization: "Imobilização curta em posição neutra, seguida de bota ou órtese. Protocolos mais rápidos dependem da qualidade do reparo e procedimentos associados.",
    weightBearing: "Descarga inicial curta; progressão de carga protegida após cicatrização da ferida, conforme estabilidade e procedimentos osteocondrais ou ósseos associados.",
    rehab: [
      { window: "0-2 semanas", weightBearing: "Sem carga ou toque", focus: "Proteção, edema, ferida e mobilidade dos dedos/joelho." },
      { window: "2-6 semanas", weightBearing: "Progressão em bota", focus: "Dorsiflexão e flexão plantar; evitar inversão forçada." },
      { window: "6-12 semanas", weightBearing: "Carga plena com órtese", focus: "Amplitude, força dos fibulares, equilíbrio e controle unipodal." },
      { window: "3-5 meses", weightBearing: "Impacto progressivo", focus: "Corrida, salto, aterrissagem, mudança de direção e confiança." },
      { window: "4-6 meses", weightBearing: "Retorno se critérios", focus: "Testes de salto/agilidade, força, ausência de falseio e tolerância ao treino." },
    ],
    followup: "Monitorar estabilidade, amplitude, função dos fibulares e sintomas neurais. Dor persistente exige reavaliar lesão osteocondral, impacto, subtalar ou alinhamento. Manter treino proprioceptivo e suporte externo durante a retomada esportiva.",
  },
  complications: [
    { name: "Instabilidade recorrente", detail: "Pode ocorrer por tecido ruim, hiperlaxidão, deformidade ou retorno precoce.", prevention: "Seleção, correção de fatores de risco e progressão funcional." },
    { name: "Sobre-restrição e rigidez", detail: "Tensionamento excessivo reduz inversão e pode alterar a subtalar.", prevention: "Tensionar em posição anatômica e iniciar mobilidade segura." },
    { name: "Neuropraxia cutânea", detail: "Irritação do nervo fibular superficial ou sural.", prevention: "Identificação, proteção e portais/incisão seguros." },
    { name: "Dor persistente", detail: "Frequentemente ligada a lesão intra-articular ou tendínea não tratada.", prevention: "Inventário clínico e articular completo." },
  ],
  evidence: [
    {
      id: "hou-2024",
      claim: "Ensaio randomizado mostrou melhora com treinamento proprioceptivo e Broström-Gould; cirurgia gerou estabilidade mecânica mais rápida, enquanto treinamento melhorou controle dinâmico.",
      takeaway: "Estrutura e controle neuromuscular são componentes complementares, não concorrentes.",
      level: "II",
      studyType: "Ensaio clínico randomizado",
      era: "atual",
      citation: { authors: "Hou Z, Ren S, Hu Y, et al.", title: "Comparison of Subjective and Biomechanical Outcomes Between Proprioceptive Training and Modified Broström-Gould Surgery for Chronic Ankle Instability: A Randomized Controlled Trial", journal: "Orthopaedic Journal of Sports Medicine", year: 2024, pmid: "39291124", doi: "10.1177/23259671241274138" },
    },
    {
      id: "hupperets-2009",
      claim: "Treino proprioceptivo domiciliar após entorse reduziu recorrências em ensaio randomizado.",
      takeaway: "Propriocepção deve permanecer na prevenção secundária mesmo após melhora ou cirurgia.",
      level: "I",
      studyType: "Ensaio clínico randomizado",
      era: "classico",
      citation: { authors: "Hupperets MDW, Verhagen EALM, van Mechelen W", title: "Effect of unsupervised home based proprioceptive training on recurrences of ankle sprain: randomised controlled trial", journal: "BMJ", year: 2009, pmid: "19589822", doi: "10.1136/bmj.b2684" },
    },
    {
      id: "bell-2006",
      claim: "Seguimento de 26 anos do Broström mostrou função boa ou excelente na maioria dos pacientes ativos avaliados.",
      takeaway: "Reparo anatômico pode oferecer estabilidade durável quando indicação e tecido são adequados.",
      level: "IV",
      studyType: "Série de casos de longo prazo",
      era: "classico",
      citation: { authors: "Bell SJ, Mologne TS, Sitler DF, Cox JS", title: "Twenty-six-year results after Broström procedure for chronic lateral ankle instability", journal: "The American Journal of Sports Medicine", year: 2006, pmid: "16399935", doi: "10.1177/0363546505282616" },
    },
    {
      id: "park-2016",
      claim: "Frouxidão ligamentar generalizada foi preditor independente de falha após Broström modificado em coorte de 199 tornozelos.",
      takeaway: "Hiperlaxidão deve alterar aconselhamento e pode justificar reforço ou reconstrução.",
      level: "III",
      studyType: "Coorte prognóstica",
      era: "atual",
      citation: { authors: "Park KH, Lee JW, Suh JW, Shin MH, Choi WJ", title: "Generalized Ligamentous Laxity Is an Independent Predictor of Poor Outcomes After the Modified Broström Procedure for Chronic Lateral Ankle Instability", journal: "The American Journal of Sports Medicine", year: 2016, pmid: "27480980", doi: "10.1177/0363546516656183" },
    },
    {
      id: "kong-2021",
      claim: "Reabilitação pós-operatória estruturada melhorou função e equilíbrio após cirurgia de instabilidade crônica em ensaio randomizado.",
      takeaway: "Cirurgia não substitui reabilitação neuromuscular sistemática.",
      level: "II",
      studyType: "Ensaio clínico randomizado",
      era: "atual",
      citation: { authors: "Kong DH, Lee GS, Park SH, et al.", title: "Effectiveness of Hospital-Based Systemic Rehabilitation in Improving Ankle Function after Surgery in Chronic Ankle Instability Patients", journal: "BioMed Research International", year: 2021, pmid: "33575340", doi: "10.1155/2021/6695096" },
    },
  ],
  pearls: [
    "Instabilidade crônica é mecânica e funcional; medir ambas.",
    "Examinar cavo-varo e primeiro raio antes de culpar apenas o LTFA.",
    "Dor persistente pede busca de osteocondral, impacto, fibulares e sindesmose.",
    "Broström-Gould preserva anatomia e movimento quando há tecido adequado.",
    "Treino proprioceptivo continua obrigatório após reparo bem-sucedido.",
  ],
  pitfalls: [
    "Indicar cirurgia por RM sem falseio e exame correlato.",
    "Chamar reabilitação de falha sem treino progressivo de salto e mudança de direção.",
    "Ignorar hiperlaxidão ou cavo-varo antes do reparo.",
    "Lesar o nervo fibular superficial na via ou artroscopia.",
    "Sobre-tensionar o reparo e restringir subtalar.",
  ],
  figures: [
    { id: "instabilidade-lateral-tornozelo:anatomia", caption: "LTFA, LCF e talofibular posterior em relação aos tendões fibulares.", alt: "Vista lateral do tornozelo mostrando ligamentos laterais e tendões fibulares.", kind: "diagram" },
    { id: "instabilidade-lateral-tornozelo:cadeia-cinematica", caption: "Componentes mecânico e funcional da instabilidade crônica.", alt: "Cadeia de entorse, déficit proprioceptivo, falseio e recorrência.", kind: "diagram" },
    { id: "instabilidade-lateral-tornozelo:exame", caption: "Gaveta anterior para LTFA e inclinação talar para LCF.", alt: "Testes clínicos de gaveta anterior e inclinação talar do tornozelo.", kind: "diagram" },
    { id: "instabilidade-lateral-tornozelo:imagem", caption: "Radiografia com carga, estresse e RM para lesões associadas.", alt: "Painéis de radiografia e ressonância do tornozelo com frouxidão e lesão osteocondral.", kind: "diagram" },
    { id: "instabilidade-lateral-tornozelo:brostrom", caption: "Reparo anatômico de Broström-Gould do LTFA e LCF.", alt: "Etapas do reparo dos ligamentos laterais na fíbula com reforço retinacular.", kind: "diagram" },
    { id: "instabilidade-lateral-tornozelo:retorno-esporte", caption: "Retorno por critérios de estabilidade, força, equilíbrio, salto e confiança.", alt: "Linha do tempo funcional após tratamento da instabilidade lateral do tornozelo.", kind: "diagram" },
  ],
  meta: {
    lastReviewed: "2026-07-14",
    sources: ["Hou et al., OJSM 2024", "Hupperets et al., BMJ 2009", "Bell et al., AJSM 2006", "Park et al., AJSM 2016"],
    attribution: "Conteúdo original em português brasileiro; evidências verificadas no PubMed e diagramas próprios.",
    figureReference: "Campbell's Operative Orthopaedics, 14a ed. (2021), seção de instabilidade lateral do tornozelo.",
  },
});
