import { defineTopic } from "../../types/topic";

export const topic = defineTopic({
  id: "esp-joelho-lesao-meniscal",
  slug: "lesao-meniscal",
  kind: "condicao",
  regionId: "esportiva-artroscopia",
  bone: "Joelho",
  injury: "Lesão meniscal",
  title: "Lesão meniscal",
  subtitle:
    "Distinguir ruptura traumática reparável de achado degenerativo, preservar tecido funcional e adaptar a reabilitação ao padrão reparado.",
  laterality: null,
  status: "complete",
  overview:
    "Os meniscos distribuem carga, aumentam a congruência, absorvem impacto e participam da estabilidade e propriocepção do joelho. Uma ruptura não é uma entidade única: a lesão longitudinal traumática de um atleta jovem, a alça de balde que bloqueia o joelho, a ruptura radial, a avulsão de raiz e o sinal degenerativo incidental na ressonância têm prognóstico e tratamento diferentes.\n\nDor na interlinha, derrame tardio e sintomas após rotação sugerem lesão, mas o diagnóstico exige correlação clínica. Testes de Thessaly e McMurray aumentam ou reduzem a probabilidade; a ressonância define morfologia, localização, extrusão e lesões associadas. Estalido ou travamento inespecífico não equivale a bloqueio mecânico verdadeiro.\n\nO princípio moderno é preservar o menisco. Rupturas traumáticas periféricas, longitudinais, radiais completas e de raiz devem ser reparadas quando tecnicamente possível. Meniscectomia parcial fica restrita ao fragmento instável e inviável que não pode ser estabilizado. Em rupturas degenerativas não obstrutivas, exercício é primeira linha: ensaios com placebo e fisioterapia não mostram benefício clinicamente relevante da meniscectomia artroscópica de rotina.",
  keyFacts: [
    { label: "Função", value: "Carga, congruência, estabilidade e propriocepção" },
    { label: "Prioridade", value: "Preservar e reparar tecido funcional" },
    { label: "Urgência relativa", value: "Joelho bloqueado por alça de balde deslocada" },
    { label: "Raiz", value: "Avulsão equivale biomecanicamente a meniscectomia" },
    { label: "Degenerativa", value: "Exercício antes de artroscopia" },
    { label: "Reabilitação", value: "Depende da estabilidade e do padrão reparado" },
  ],
  anatomy: {
    text:
      "O menisco medial é semicircular e menos móvel porque se fixa à cápsula e ao ligamento colateral medial; por isso sofre mais nas instabilidades crônicas do LCA. O menisco lateral é quase circular, mais móvel e separado do colateral lateral pelo hiato poplíteo. As raízes anterior e posterior ancoram cada menisco ao platô e convertem carga axial em tensão circunferencial.\n\nA vascularização entra pela periferia capsular. A zona vermelho-vermelha é periférica e melhor irrigada; a vermelho-branca é intermediária; a branco-branca, central, tem baixo potencial biológico. Vascularidade, porém, não decide sozinha: padrão, cronicidade, estabilidade, idade tecidual e lesões associadas também importam.\n\nRuptura radial interrompe as fibras circunferenciais e reduz a capacidade de distribuir carga. Avulsão da raiz posterior ou ruptura radial a até 1 cm da raiz produz extrusão e perda funcional semelhante à meniscectomia total. A lesão da rampa corresponde à junção meniscocapsular posteromedial e deve ser procurada em joelhos com LCA insuficiente.",
    figureIds: ["lesao-meniscal:anatomia", "lesao-meniscal:rm-clinica", "lesao-meniscal:padroes"],
  },
  classification: [
    {
      id: "morfologia",
      name: "Morfologia da ruptura",
      basis: "Direção do traço e efeito sobre a continuidade das fibras circunferenciais.",
      types: [
        { code: "Longitudinal", label: "Vertical longitudinal", description: "Paralela à borda; periférica e traumática costuma ser reparável. Quando deslocada, forma alça de balde.", figureId: "lesao-meniscal:padroes", figureVariant: "longitudinal" },
        { code: "Radial", label: "Radial", description: "Perpendicular às fibras circunferenciais; rupturas completas exigem reparo para restaurar a transmissão de carga.", figureId: "lesao-meniscal:padroes", figureVariant: "radial" },
        { code: "Horizontal", label: "Horizontal", description: "Divide lâminas superior e inferior; frequente no processo degenerativo e pode formar cisto parameniscal.", figureId: "lesao-meniscal:padroes", figureVariant: "horizontal" },
        { code: "Complexa", label: "Complexa / degenerativa", description: "Múltiplos planos e tecido de baixa qualidade; tratar sintomas e artrose, evitando ressecção indiscriminada.", figureId: "lesao-meniscal:padroes", figureVariant: "complexa" },
        { code: "Raiz", label: "Raiz posterior", description: "Avulsão ou ruptura radial próxima da inserção; causa extrusão e perda da tensão circunferencial.", figureId: "lesao-meniscal:raiz", figureVariant: "avulsao" },
      ],
    },
  ],
  indications: {
    operative: [
      "Alça de balde deslocada com bloqueio mecânico verdadeiro: redução e reparo em tempo oportuno.",
      "Ruptura traumática periférica longitudinal instável em paciente ativo.",
      "Ruptura radial completa, lesão de raiz ou rampa instável com tecido reparável.",
      "Lesão meniscal associada à reconstrução do LCA quando instável à sondagem.",
      "Fragmento instável irreparável após falha de tratamento: meniscectomia parcial mínima.",
    ],
    nonOperative: [
      "Ruptura degenerativa não obstrutiva: educação, modificação de carga, força e controle neuromuscular.",
      "Lesão pequena e estável, especialmente periférica, sem bloqueio ou derrame recorrente.",
      "Achado incidental na ressonância sem correlação clínica.",
      "Paciente com artrose dominante, em quem a ruptura é parte do processo degenerativo.",
    ],
    decisionNotes:
      "A decisão começa por três perguntas: o joelho está realmente bloqueado, o tecido é reparável e a ruptura explica os sintomas? Dor e estalidos isolados em meia-idade não justificam meniscectomia. Em lesão traumática, a preservação ganha prioridade porque cada ressecção aumenta a pressão de contato. Na raiz medial, considerar alinhamento, cartilagem, extrusão e capacidade de cumprir descarga; artrose avançada e varo não corrigido reduzem o benefício do reparo isolado.",
  },
  approaches: [
    {
      id: "portais-anteriores",
      name: "Portais artroscópicos anterolateral e anteromedial",
      indication: "Inventário, sondagem, meniscectomia limitada e reparos do corpo/corno anterior.",
      interval: "Portais junto às bordas do tendão patelar, posicionados sob transiluminação e visão direta para alcançar a lesão sem agredir cartilagem.",
      atRisk: ["Cartilagem femorotibial", "Corno anterior meniscal", "Ramo infrapatelar do nervo safeno"],
      figureId: "lesao-meniscal:reparo",
    },
    {
      id: "posteromedial",
      name: "Portal posteromedial",
      indication: "Inspeção e reparo de rampa e corno posterior medial ocultos à visão anterior.",
      interval: "Portal sob visão transintercondilar, posterior ao côndilo medial e anterior aos tendões da pata de ganso, com agulha de localização.",
      atRisk: ["Veia safena", "Nervo safeno", "Feixe poplíteo se o trajeto for excessivamente posterior"],
      figureId: "lesao-meniscal:exame-rm",
    },
  ],
  technique: [
    { n: 1, title: "Correlacionar clínica e imagem", detail: "Definir trauma, bloqueio verdadeiro, interlinha dolorosa, derrame, estabilidade ligamentar e alinhamento. Na RM, registrar padrão, zona, extrusão, raiz, cartilagem e edema ósseo.", figureId: "lesao-meniscal:exame-rm", tips: ["Examinar o joelho inteiro; ruptura degenerativa pode ser incidental"], pitfalls: ["Operar o laudo sem reproduzir o quadro clínico"] },
    { n: 2, title: "Inventariar e testar estabilidade", detail: "Visualizar ambos os compartimentos e sondar bordas, raízes e junções meniscocapsulares. Reduzir fragmento deslocado e avaliar qualidade, comprimento e possibilidade de coaptação.", figureId: "lesao-meniscal:padroes", tips: ["Usar visão transintercondilar para a rampa"], pitfalls: ["Considerar estável sem sondagem sistemática"] },
    { n: 3, title: "Preparar sem destruir", detail: "Regularizar delicadamente as margens e estimular a zona periférica com raspagem ou trepanação quando indicado. Preservar o máximo de tecido e evitar ampliar artificialmente a lesão.", figureId: "lesao-meniscal:reparo", tips: ["Preparar até obter bordas viáveis, não até criar um defeito maior"], pitfalls: ["Desbridamento agressivo que inviabiliza o reparo"] },
    { n: 4, title: "Escolher a configuração do reparo", detail: "All-inside é útil no corno posterior; inside-out oferece versatilidade no corpo; outside-in atende corno anterior. Suturas verticais abrangem melhor as fibras circunferenciais. Combinar configurações em rupturas radiais.", figureId: "lesao-meniscal:reparo", tips: ["Colocar pontos dos dois lados do traço radial"], pitfalls: ["Implante proeminente contra cartilagem ou estruturas neurovasculares"] },
    { n: 5, title: "Reinserir a raiz no centro anatômico", detail: "Na avulsão de raiz reparável, preparar a inserção, passar suturas bloqueantes e reduzi-las por túnel transtibial ou âncora. Confirmar que a raiz assenta sem ponte de tecido e sem extrusão excessiva.", figureId: "lesao-meniscal:raiz", tips: ["Centralizar o túnel na inserção anatômica"], pitfalls: ["Túnel não anatômico que mantém o menisco sem função"] },
    { n: 6, title: "Testar e definir a proteção", detail: "Sondar toda a extensão após o reparo, documentar padrão e estabilidade e vincular a reabilitação ao tipo de sutura. Reparo de raiz/radial exige proteção maior que lesão longitudinal periférica estável.", figureId: "lesao-meniscal:reabilitacao", tips: ["Escrever no relatório as restrições específicas"], pitfalls: ["Aplicar o mesmo protocolo a todos os padrões"] },
  ],
  postop: {
    immobilization: "Órtese articulada pode proteger reparos extensos, radiais ou de raiz; não é obrigatória após meniscectomia parcial mínima.",
    weightBearing: "Após reparo longitudinal estável, carga protegida pode progredir cedo. Reparos de raiz e radiais completos geralmente permanecem sem carga por cerca de 6 semanas.",
    rehab: [
      { window: "0-6 semanas", weightBearing: "Conforme padrão; raiz/radial sem carga", focus: "Extensão completa, controle do derrame, quadríceps e flexão protegida conforme o reparo." },
      { window: "6-12 semanas", weightBearing: "Progressão até carga plena", focus: "Amplitude, força, bicicleta e controle unipodal sem reação articular." },
      { window: "3-4 meses", weightBearing: "Corrida se critérios", focus: "Força simétrica, agachamento, aterrissagem e corrida linear." },
      { window: "4-6 meses", weightBearing: "Retorno gradual", focus: "Mudança de direção e esporte após reparo; raiz/radial pode exigir progressão mais lenta." },
    ],
    followup: "Monitorar derrame, dor na interlinha, amplitude e força. Dor mecânica recorrente ou bloqueio após novo trauma exige reavaliação. A RM pós-reparo pode permanecer alterada e deve ser correlacionada à clínica.",
  },
  complications: [
    { name: "Falha do reparo", detail: "Persistência ou nova ruptura por tecido ruim, instabilidade, trauma ou retorno precoce.", prevention: "Seleção adequada, estabilidade ligamentar e progressão por critérios." },
    { name: "Lesão neurovascular", detail: "Risco maior em suturas inside-out posteriores.", prevention: "Incisão de proteção e afastador junto à cápsula." },
    { name: "Rigidez", detail: "Perda de amplitude por proteção excessiva ou inflamação.", prevention: "Extensão imediata e flexão progressiva dentro das restrições." },
    { name: "Progressão degenerativa", detail: "Mais relacionada à perda de tecido e à lesão condral associada.", prevention: "Preservar menisco e corrigir instabilidade/alinhamento relevantes." },
  ],
  evidence: [
    {
      id: "fidelity-2013",
      claim: "No FIDELITY, meniscectomia parcial não foi superior à cirurgia simulada em ruptura degenerativa sem artrose avançada.",
      takeaway: "Ruptura degenerativa não obstrutiva não justifica artroscopia de rotina.",
      level: "I",
      studyType: "Ensaio randomizado controlado por placebo",
      era: "classico",
      citation: { authors: "Sihvonen R, Paavola M, Malmivaara A, et al.; FIDELITY Group", title: "Arthroscopic partial meniscectomy versus sham surgery for a degenerative meniscal tear", journal: "The New England Journal of Medicine", year: 2013, pmid: "24369076", doi: "10.1056/NEJMoa1305189" },
    },
    {
      id: "escape-2018",
      claim: "No ESCAPE, fisioterapia estruturada foi não inferior à meniscectomia para função em pacientes de 45 a 70 anos com ruptura não obstrutiva.",
      takeaway: "Exercício supervisionado é o tratamento inicial da ruptura degenerativa sintomática.",
      level: "I",
      studyType: "Ensaio randomizado multicêntrico de não inferioridade",
      era: "atual",
      citation: { authors: "van de Graaf VA, Noorduyn JCA, Willigenburg NW, et al.; ESCAPE Research Group", title: "Effect of Early Surgery vs Physical Therapy on Knee Function Among Patients With Nonobstructive Meniscal Tears: The ESCAPE Randomized Clinical Trial", journal: "JAMA", year: 2018, pmid: "30285177", doi: "10.1001/jama.2018.13308" },
    },
    {
      id: "omex-2025",
      claim: "No seguimento de 10 anos do OMEX, exercício e meniscectomia mantiveram resultados clínicos semelhantes, sem vantagem tardia da cirurgia.",
      takeaway: "A ausência de benefício da meniscectomia degenerativa persiste no longo prazo.",
      level: "I",
      studyType: "Seguimento de ensaio clínico randomizado",
      era: "atual",
      citation: { authors: "Berg B, Roos EM, Englund M, et al.", title: "Arthroscopic partial meniscectomy versus exercise therapy for degenerative meniscal tears: 10-year follow-up of the OMEX randomised controlled trial", journal: "British Journal of Sports Medicine", year: 2025, pmid: "39326908", doi: "10.1136/bjsports-2024-108644" },
    },
    {
      id: "chung-raiz-2015",
      claim: "Em comparação com meniscectomia parcial, reinserção da raiz posterior medial apresentou melhores resultados clínicos e radiográficos em seguimento mínimo de cinco anos.",
      takeaway: "Raiz reparável deve ser reinserida quando cartilagem, alinhamento e paciente permitem.",
      level: "III",
      studyType: "Coorte comparativa",
      era: "atual",
      citation: { authors: "Chung KS, Ha JK, Yeom CH, et al.", title: "Comparison of Clinical and Radiologic Results Between Partial Meniscectomy and Refixation of Medial Meniscus Posterior Root Tears: A Minimum 5-Year Follow-up", journal: "Arthroscopy", year: 2015, pmid: "26095821", doi: "10.1016/j.arthro.2015.03.035" },
    },
  ],
  pearls: [
    "Bloqueio verdadeiro é incapacidade fixa de extensão, não estalido ocasional.",
    "Toda lesão deve ser descrita por menisco, segmento, padrão, zona e estabilidade.",
    "Preservar tecido é mais importante que obter uma borda artroscópica esteticamente regular.",
    "Ruptura radial completa e raiz não são lesões pequenas do ponto de vista biomecânico.",
    "Reabilitação deve seguir o padrão reparado, não apenas o nome 'sutura meniscal'.",
  ],
  pitfalls: [
    "Confundir achado degenerativo na RM com causa obrigatória da dor.",
    "Ressecar alça de balde reparável em paciente jovem.",
    "Não procurar lesão da rampa durante reconstrução do LCA.",
    "Liberar carga e flexão profundas precocemente após reparo de raiz.",
    "Ignorar varo e artrose ao indicar reparo isolado da raiz medial.",
  ],
  figures: [
    { id: "lesao-meniscal:anatomia", caption: "Anatomia meniscal, raízes, mobilidade e zonas vasculares.", alt: "Vista superior do platô tibial com meniscos medial e lateral e suas raízes.", kind: "diagram" },
    { id: "lesao-meniscal:rm-clinica", caption: "Ressonância coronal com ruptura meniscal e líquido alcançando a superfície articular.", alt: "Ressonância magnética coronal de joelho com ruptura meniscal.", kind: "mri", source: { label: "Ciernik M / Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:MRI_meniscus_tear.jpg", license: "CC BY-SA 4.0" } },
    { id: "lesao-meniscal:padroes", caption: "Padrões de ruptura e efeito sobre as fibras circunferenciais.", alt: "Comparação entre rupturas longitudinal, radial, horizontal, complexa e em alça de balde.", kind: "diagram" },
    { id: "lesao-meniscal:exame-rm", caption: "Correlação entre exame, plano da ressonância e localização da lesão.", alt: "Joelho examinado e cortes esquemáticos de ressonância do menisco.", kind: "diagram" },
    { id: "lesao-meniscal:reparo", caption: "Reparo all-inside, inside-out e outside-in conforme a localização.", alt: "Técnicas de sutura meniscal com pontos verticais estabilizando o traço.", kind: "diagram" },
    { id: "lesao-meniscal:raiz", caption: "Avulsão da raiz posterior e reinserção transtibial anatômica.", alt: "Menisco extruso antes e reinserido por túnel tibial após o reparo da raiz.", kind: "diagram" },
    { id: "lesao-meniscal:reabilitacao", caption: "Proteção proporcional ao padrão: longitudinal, radial e raiz.", alt: "Linha do tempo comparando protocolos após diferentes reparos meniscais.", kind: "diagram" },
  ],
  meta: {
    lastReviewed: "2026-07-14",
    sources: ["FIDELITY, NEJM 2013", "ESCAPE, JAMA 2018", "OMEX, BJSM 2025", "Chung et al., Arthroscopy 2015"],
    attribution: "Conteúdo original em português brasileiro; evidências verificadas no PubMed e diagramas próprios.",
    figureReference: "Campbell's Operative Orthopaedics, 14a ed. (2021), seção de lesões meniscais e artroscopia do joelho.",
  },
});
