import { defineTopic } from "../../types/topic";

export const topic = defineTopic({
  id: "esp-ombro-lesao-labral-bankart",
  slug: "lesao-labral-bankart",
  kind: "condicao",
  regionId: "esportiva-artroscopia",
  bone: "Ombro",
  injury: "Instabilidade anterior e lesão de Bankart",
  title: "Lesão labral de Bankart",
  subtitle:
    "Tratar a instabilidade anterior pela combinação de risco do paciente, qualidade capsulolabral e perda óssea glenoidal e umeral.",
  laterality: null,
  status: "complete",
  overview:
    "A lesão de Bankart é o destacamento do labrum e do complexo capsuloligamentar anteroinferior após luxação anterior. Ela raramente deve ser analisada isoladamente: idade, esporte de contato, número de episódios, hiperlaxidão, perda óssea da glenoide e defeito de Hill-Sachs determinam o risco de recorrência e o procedimento necessário.\n\nNo primeiro episódio, a prioridade é redução segura, exame neurovascular e radiografias pós-redução. Em jovem atleta, a chance de recorrência é alta e estabilização precoce pode ser discutida. Na instabilidade recorrente, tomografia tridimensional quantifica a glenoide e o Hill-Sachs; ressonância ou artro-RM avalia labrum, cápsula, manguito e lesões associadas.\n\nReparo artroscópico de Bankart funciona quando há tecido reparável e perda óssea baixa com Hill-Sachs contido na trilha glenoidal. Hill-Sachs fora da trilha com perda glenoidal subcrítica pode exigir remplissage. Perda glenoidal relevante, fragmento não reconstruível, atleta de colisão de alto risco ou falha prévia deslocam a decisão para aumento ósseo, frequentemente Latarjet. Usar um limiar isolado ignora a interação bipolar.",
  keyFacts: [
    { label: "Lesão", value: "Labrum e cápsula anteroinferiores destacados" },
    { label: "Maior risco", value: "Jovem, contato, hiperlaxidão e recorrência" },
    { label: "Imagem óssea", value: "TC 3D com método do círculo perfeito" },
    { label: "Interação", value: "Perda glenoidal + Hill-Sachs = lesão bipolar" },
    { label: "Bankart isolado", value: "Tecido bom, baixa perda e Hill-Sachs na trilha" },
    { label: "Remplissage", value: "Hill-Sachs fora da trilha com glenoide preservada/subcrítica" },
    { label: "Aumento ósseo", value: "Perda glenoidal relevante ou falha de partes moles" },
  ],
  anatomy: {
    text:
      "O labrum aprofunda a glenoide e serve de inserção para cápsula e ligamentos glenoumerais. Em abdução e rotação externa, a banda anterior do ligamento glenoumeral inferior é o principal estabilizador contra translação anterior. A lesão de Bankart separa esse complexo da borda entre aproximadamente 3 e 6 horas no ombro direito.\n\nVariantes modificam a estratégia. Na ALPSA, o complexo cicatriza medializado no colo e precisa ser mobilizado. Na Perthes, o labrum se destaca com periósteo preservado. A GLAD associa lesão condral. A HAGL é avulsão umeral do ligamento glenoumeral inferior e não é corrigida por âncoras na glenoide. O Bankart ósseo inclui fragmento anteroinferior.\n\nA impactação posterolateral da cabeça durante a luxação produz Hill-Sachs. A trilha glenoidal representa a faixa da cabeça que permanece em contato com a glenoide em abdução e rotação externa. Perda glenoidal estreita essa faixa; se o intervalo de Hill-Sachs ultrapassa a trilha, a lesão é fora da trilha e pode engajar.",
    figureIds: ["lesao-labral-bankart:anatomia", "lesao-labral-bankart:rm-clinica", "lesao-labral-bankart:lesoes-associadas"],
  },
  classification: [
    {
      id: "trilha-glenoidal",
      name: "Trilha glenoidal",
      basis: "Relação entre o intervalo de Hill-Sachs e a largura da trilha corrigida pela perda glenoidal.",
      note: "Trilha glenoidal ≈ 0,83 × diâmetro glenoidal intacto − perda óssea. Comparar com o intervalo de Hill-Sachs, não apenas com a largura do defeito.",
      types: [
        { code: "Na trilha", label: "Hill-Sachs contido", description: "Intervalo de Hill-Sachs menor que a trilha; menor risco de engajamento após restauração capsulolabral.", figureId: "lesao-labral-bankart:trilha-glenoidal", figureVariant: "on-track" },
        { code: "Fora da trilha", label: "Hill-Sachs ultrapassa a trilha", description: "Defeito estende-se medialmente além da zona de contato; Bankart isolado tem maior risco de falha.", figureId: "lesao-labral-bankart:trilha-glenoidal", figureVariant: "off-track" },
      ],
    },
  ],
  indications: {
    operative: [
      "Instabilidade anterior recorrente ou subluxações que limitam esporte/trabalho.",
      "Primeiro episódio em jovem atleta de colisão ou com fatores anatômicos de alto risco, após decisão compartilhada.",
      "Bankart reparável com perda óssea baixa: reparo capsulolabral artroscópico.",
      "Hill-Sachs fora da trilha e perda glenoidal baixa/subcrítica: Bankart associado a remplissage.",
      "Perda glenoidal relevante, fragmento não reparável, falha prévia ou risco extremo: aumento ósseo glenoidal.",
      "HAGL sintomática ou lesão óssea que exija procedimento específico.",
    ],
    nonOperative: [
      "Primeira luxação em paciente de menor risco após redução, curto período de conforto e reabilitação.",
      "Paciente sem apreensão ou recorrência que aceita modificar exposição de risco.",
      "Contraindicação clínica ou baixa demanda com preferência por manejo funcional.",
    ],
    decisionNotes:
      "A escolha não deve usar apenas 'percentual crítico'. Quantificar glenoide, intervalo de Hill-Sachs e trilha; acrescentar idade, esporte, hiperlaxidão, número de eventos e qualidade capsular. Perdas a partir de cerca de 13,5% foram associadas a pior função após Bankart em algumas coortes, enquanto perdas de 20–25% são classicamente consideradas críticas. Entre esses valores existe zona cinzenta: remplissage, Latarjet ou outro enxerto dependem da lesão bipolar e do perfil. Latarjet oferece estabilidade, mas traz risco neurovascular, pseudartrose, posicionamento do enxerto e artrose; não deve ser automático.",
  },
  approaches: [
    {
      id: "portais-bankart",
      name: "Portais posterior, anterossuperior e anteroinferior",
      indication: "Inventário, mobilização capsulolabral e colocação inferior de âncoras.",
      interval: "Portal posterior para visão; anterossuperior no intervalo para visão alternativa; anteroinferior baixo, acima do subescapular, para acesso à borda de 5–6 horas.",
      atRisk: ["Nervo musculocutâneo medial ao coracoide", "Nervo axilar inferior à cápsula", "Cartilagem glenoidal"],
      figureId: "lesao-labral-bankart:reparo-bankart",
    },
    {
      id: "deltopeitoral-latarjet",
      name: "Via deltopeitoral para Latarjet",
      indication: "Aumento ósseo com coracoide em perda glenoidal relevante ou falha de partes moles.",
      interval: "Intervalo deltopeitoral, osteotomia do coracoide, divisão do subescapular no sentido das fibras e capsulotomia para fixar o enxerto rente à superfície glenoidal.",
      atRisk: ["Nervo musculocutâneo", "Nervo axilar", "Nervo supraescapular com parafusos longos"],
      figureId: "lesao-labral-bankart:algoritmo-osseo",
    },
  ],
  technique: [
    { n: 1, title: "Estadiar risco e osso antes da cirurgia", detail: "Registrar episódios, idade, esporte, hiperlaxidão e exame de apreensão. Quantificar perda glenoidal e Hill-Sachs na TC 3D e calcular se está na ou fora da trilha.", figureId: "lesao-labral-bankart:trilha-glenoidal", tips: ["Usar o intervalo de Hill-Sachs, não a largura isolada"], pitfalls: ["Planejar Bankart sem medir perda óssea"] },
    { n: 2, title: "Inventariar toda a instabilidade", detail: "Examinar sob anestesia e artroscopia: labrum, cápsula, ALPSA, HAGL, GLAD, SLAP, manguito e defeitos ósseos. Confirmar que o procedimento planejado corresponde à anatomia real.", figureId: "lesao-labral-bankart:lesoes-associadas", tips: ["Procurar HAGL quando o labrum parece insuficiente para explicar a frouxidão"], pitfalls: ["Reparar apenas o que é óbvio na borda anterior"] },
    { n: 3, title: "Mobilizar e preparar a borda", detail: "Liberar o complexo medializado até que alcance a borda sem tensão, preservando tecido. Criar leito sangrante no colo sem remover osso estrutural.", figureId: "lesao-labral-bankart:reparo-bankart", tips: ["A mobilização adequada restaura volume e posição"], pitfalls: ["Fixar ALPSA medializada sem liberação"] },
    { n: 4, title: "Fixar de inferior para superior", detail: "Inserir a primeira âncora o mais inferior possível e avançar superiormente. Capturar cápsula inferior e labrum para obter retensionamento seletivo, evitando excesso em posição neutra.", figureId: "lesao-labral-bankart:reparo-bankart", tips: ["Âncora inferior é central para restaurar o IGHL"], pitfalls: ["Poucas âncoras altas, deixando bolsa inferior"] },
    { n: 5, title: "Adicionar remplissage quando indicado", detail: "Com Bankart ainda acessível, preparar o Hill-Sachs e colocar âncoras no defeito; após o reparo anterior, fixar cápsula posterior e infraespinal ao leito sem sobre-restringir rotação externa.", figureId: "lesao-labral-bankart:algoritmo-osseo", figureVariant: "remplissage", tips: ["Planejar remplissage antes de fechar o compartimento anterior"], pitfalls: ["Usar para perda glenoidal crítica que exige restauração óssea"] },
    { n: 6, title: "Restaurar a glenoide quando partes moles não bastam", detail: "No Latarjet, posicionar coracoide abaixo do equador e rente à cartilagem, com fixação estável e parafusos de comprimento seguro. Preservar o tendão conjunto e evitar degrau lateral.", figureId: "lesao-labral-bankart:algoritmo-osseo", figureVariant: "latarjet", tips: ["Posição do enxerto determina estabilidade e artrose"], pitfalls: ["Enxerto lateral proeminente ou medial ineficaz"] },
    { n: 7, title: "Testar estabilidade e documentar restrições", detail: "Avaliar translação, tensão capsular e rotação externa ao final. Documentar procedimento, perda óssea e reparos associados para orientar proteção e retorno ao contato.", figureId: "lesao-labral-bankart:reabilitacao", tips: ["Comparar rotação com o lado oposto sem forçar o reparo"], pitfalls: ["Retorno baseado apenas no tempo"] },
  ],
  postop: {
    immobilization: "Tipoia por cerca de 3–4 semanas após Bankart, ajustada a remplissage, Latarjet e qualidade tecidual.",
    weightBearing: "Sem apoio, carga ou posição de abdução e rotação externa forçada no início. Cotovelo, punho e mão movem-se desde cedo.",
    rehab: [
      { window: "0-4 semanas", weightBearing: "Sem carga", focus: "Proteção, dor, mobilidade passiva segura e controle escapular." },
      { window: "4-12 semanas", weightBearing: "Sem contato", focus: "Recuperar amplitude progressiva, rotação sem forçar e ativação do manguito." },
      { window: "3-5 meses", weightBearing: "Força progressiva", focus: "Manguito, escápula, cadeia cinética e posição acima da cabeça." },
      { window: "5-7 meses", weightBearing: "Contato gradual", focus: "Força simétrica, estabilidade, confiança e tarefas específicas do esporte." },
    ],
    followup: "Avaliar apreensão, amplitude, força e estabilidade. Após Latarjet, confirmar consolidação e posição do enxerto antes de contato. Remplissage pode reduzir discretamente rotação externa, mas perda funcional relevante exige correção de rigidez e mecânica escapular.",
  },
  complications: [
    { name: "Recorrência", detail: "Associada a jovem, contato, hiperlaxidão, osso não tratado e falha técnica.", prevention: "Estadiar lesão bipolar e escolher procedimento compatível." },
    { name: "Rigidez e perda de rotação externa", detail: "Pode ocorrer por plicatura excessiva ou remplissage muito tenso.", prevention: "Tensionamento seletivo e reabilitação progressiva." },
    { name: "Complicações do Latarjet", detail: "Lesão neural, pseudartrose, lise, parafuso e artrose por enxerto lateral.", prevention: "Via anatômica, enxerto rente e fixação segura." },
    { name: "Artropatia da instabilidade", detail: "Relacionada a episódios repetidos, defeitos condráis e procedimentos prévios.", prevention: "Evitar recorrência e tratar lesão estrutural adequada ao risco." },
  ],
  evidence: [
    {
      id: "yamamoto-2007",
      claim: "Estudo anatômico definiu a trilha glenoidal como a zona de contato e demonstrou que Hill-Sachs medial à trilha tem risco de engajamento.",
      takeaway: "A interação entre glenoide e úmero é mais útil que medir cada defeito isoladamente.",
      level: "V",
      studyType: "Estudo biomecânico cadavérico",
      era: "classico",
      citation: { authors: "Yamamoto N, Itoi E, Abe H, et al.", title: "Contact between the glenoid and the humeral head in abduction, external rotation, and horizontal extension: a new concept of glenoid track", journal: "Journal of Shoulder and Elbow Surgery", year: 2007, pmid: "17644006", doi: "10.1016/j.jse.2006.12.012" },
    },
    {
      id: "bassigny-2007",
      claim: "A coorte que originou o ISIS identificou idade jovem, esporte de risco, hiperlaxidão e defeitos ósseos como preditores de recorrência após Bankart.",
      takeaway: "Risco do paciente deve ser somado à anatomia antes de escolher partes moles isoladas.",
      level: "III",
      studyType: "Coorte prospectiva",
      era: "classico",
      citation: { authors: "Balg F, Boileau P", title: "The instability severity index score. A simple pre-operative score to select patients for arthroscopic or open shoulder stabilisation", journal: "The Journal of Bone and Joint Surgery. British Volume", year: 2007, pmid: "17998184", doi: "10.1302/0301-620X.89B11.18962" },
    },
    {
      id: "macdonald-remplissage-2021",
      claim: "Em pacientes com Hill-Sachs e perda glenoidal menor que 15%, Bankart com remplissage reduziu redislocação em dois anos comparado ao Bankart isolado.",
      takeaway: "Remplissage reduz recorrência na lesão umeral de risco quando a glenoide não exige grande reconstrução.",
      level: "I",
      studyType: "Ensaio clínico randomizado",
      era: "atual",
      citation: { authors: "MacDonald P, McRae S, Old J, et al.", title: "Arthroscopic Bankart repair with and without arthroscopic infraspinatus remplissage in anterior shoulder instability with a Hill-Sachs defect: a randomized controlled trial", journal: "Journal of Shoulder and Elbow Surgery", year: 2021, pmid: "33373683", doi: "10.1016/j.jse.2020.11.013" },
    },
    {
      id: "woodmass-remplissage-2024",
      claim: "No seguimento médio de quatro anos do ensaio, redislocação foi 22% no Bankart isolado e 8% com remplissage; instabilidade total foi 30% versus 10%.",
      takeaway: "O benefício do remplissage persistiu no médio prazo na população selecionada.",
      level: "I",
      studyType: "Seguimento de ensaio clínico randomizado",
      era: "atual",
      citation: { authors: "Woodmass JM, McRae S, Lapner P, et al.", title: "Arthroscopic Bankart Repair With Remplissage in Anterior Shoulder Instability Results in Fewer Redislocations Than Bankart Repair Alone at Medium-term Follow-up of a Randomized Controlled Trial", journal: "The American Journal of Sports Medicine", year: 2024, pmid: "38874505", doi: "10.1177/03635465241254063" },
    },
    {
      id: "fabbriciani-2004",
      claim: "Ensaio prospectivo mostrou resultados comparáveis entre reparo artroscópico e aberto de Bankart isolado com âncoras em pacientes selecionados.",
      takeaway: "Artroscopia é efetiva quando seleção e técnica respeitam anatomia e perda óssea.",
      level: "I",
      studyType: "Ensaio clínico randomizado",
      era: "classico",
      citation: { authors: "Fabbriciani C, Milano G, Demontis A, et al.", title: "Arthroscopic versus open treatment of Bankart lesion of the shoulder: a prospective randomized study", journal: "Arthroscopy", year: 2004, pmid: "15122134", doi: "10.1016/j.arthro.2004.03.001" },
    },
  ],
  pearls: [
    "Toda instabilidade anterior recorrente exige medir osso antes de escolher procedimento.",
    "O intervalo de Hill-Sachs inclui defeito mais ponte óssea até a inserção do manguito.",
    "Mobilizar ALPSA até a borda é parte essencial do reparo.",
    "A primeira âncora baixa restaura a banda anterior do ligamento glenoumeral inferior.",
    "Remplissage trata o defeito umeral; Latarjet restaura glenoide e acrescenta efeito de tipoia.",
  ],
  pitfalls: [
    "Aplicar Bankart isolado sem quantificar perda óssea bipolar.",
    "Usar um único percentual como decisão automática para todos os pacientes.",
    "Fixar labrum medializado sem mobilização adequada.",
    "Ignorar HAGL, GLAD ou falha capsular.",
    "Posicionar enxerto do coracoide lateral à cartilagem.",
    "Liberar contato sem força, estabilidade, confiança e consolidação quando aplicável.",
  ],
  figures: [
    { id: "lesao-labral-bankart:anatomia", caption: "Labrum anteroinferior e ligamento glenoumeral inferior na posição de risco.", alt: "Vista da glenoide com lesão de Bankart e tensão do ligamento glenoumeral inferior.", kind: "diagram" },
    { id: "lesao-labral-bankart:rm-clinica", caption: "Ressonância axial com fragmento ósseo anteroinferior da glenoide, compatível com Bankart ósseo.", alt: "Ressonância magnética axial do ombro com lesão óssea de Bankart na glenoide anteroinferior.", kind: "mri", source: { label: "RSatUSZ / Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:MRI._Bony_Bankart_lesion_at_the_inferior_glenoid..jpg", license: "CC BY-SA 3.0" } },
    { id: "lesao-labral-bankart:lesoes-associadas", caption: "Bankart, ALPSA, HAGL, GLAD, Bankart ósseo e Hill-Sachs.", alt: "Painéis comparando lesões associadas à instabilidade anterior do ombro.", kind: "diagram" },
    { id: "lesao-labral-bankart:perda-ossea", caption: "Círculo perfeito quantifica perda glenoidal e fragmento anteroinferior.", alt: "En face da glenoide com círculo inferior e cálculo percentual da perda óssea.", kind: "diagram" },
    { id: "lesao-labral-bankart:trilha-glenoidal", caption: "Hill-Sachs na trilha versus fora da trilha após correção da perda glenoidal.", alt: "Cabeça umeral com trilha glenoidal e defeitos de Hill-Sachs contido e não contido.", kind: "diagram" },
    { id: "lesao-labral-bankart:reparo-bankart", caption: "Mobilização e reparo capsulolabral de inferior para superior.", alt: "Âncoras na borda anterior da glenoide restaurando labrum e cápsula.", kind: "diagram" },
    { id: "lesao-labral-bankart:algoritmo-osseo", caption: "Bankart isolado, remplissage ou aumento ósseo conforme lesão bipolar e risco.", alt: "Algoritmo visual entre reparo de Bankart, remplissage e Latarjet.", kind: "diagram" },
    { id: "lesao-labral-bankart:reabilitacao", caption: "Proteção capsulolabral e progressão até contato e posição de apreensão.", alt: "Linha do tempo da reabilitação após estabilização anterior do ombro.", kind: "diagram" },
  ],
  meta: {
    lastReviewed: "2026-07-14",
    sources: ["Yamamoto et al., JSES 2007", "Balg & Boileau, JBJS Br 2007", "MacDonald et al., JSES 2021", "Woodmass et al., AJSM 2024"],
    attribution: "Conteúdo original em português brasileiro; evidências verificadas no PubMed e diagramas próprios.",
    figureReference: "Campbell's Operative Orthopaedics, 14a ed. (2021), seção de instabilidade glenoumeral anterior.",
  },
});
